# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  starting_hour: '8',
  finishing_hour: '10',
  time_format: '12a',
  hour_label_stepping: '1',
  columns_per_hour: '1',
  time_rounding: 'Yes',
}

# override variables
variables:
  trmnl: {
    user: {
      utc_offset: '36000',
    },
    plugin_settings: {
      instance_name: 'The workday'
    }
}
